openapi: 3.0.1
info:
  version: '1'
  title: HTTPBin-JSON
  description: HTTPBin JSON Demo Spec v1.3
  contact: 
    email: david.macdonald@konghq.com

servers:
  - url: https://httpbin.konghq.com

tags:
  - name: json
    description: Operations for testing json responses

paths:
  /json:
    get:
      summary: Returns the json payload only.
      description: JSON service
      operationId: v1GetJson
      tags:
        - json
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  slideshow:
                    type: object
                    properties:
                      author:
                        type: string
                      date:
                        type: string
                      title:
                        type: string
                      slides:
                        type: array
                        items:
                          type: object
                          properties:
                            title:
                              type: string
                            type:
                              type: string
                            items:
                              type: array
                              items:
                                type: string
                          required:
                            - title
                            - type
                    required:
                      - author
                      - date
                      - title
                      - slides
                required:
                  - slideshow
